### ISSUE TITLE
 Suggestions and Ideas

### ISSUE THREAD

**Issue by fakeoff0** [condolent/Warningshot#1]
Hello, I would like to suggest making cvar about the number of warnings 1/3 for example.
This will help prevent spam from chatting if the player wants to hold down the E button and intends to do damage.
At the same time to do damage 0

When I wanted to set the damage to 0, the plugin did not work.

I would like to help correct the error

L 05/12/2019 - 06:49:10: [SM] Exception reported: Client index 0 is invalid
L 05/12/2019 - 06:49:10: [SM] Blaming: warningshot.smx
L 05/12/2019 - 06:49:10: [SM] Call stack trace:
L 05/12/2019 - 06:49:10: [SM]   [0] IsClientInGame
L 05/12/2019 - 06:49:10: [SM]   [1] Line 67, addons\sourcemod\scripting\warningshot.sp::OnTakeDamageAlive

**Comment by jonteohr** [comment]
Error fixed
